/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * プラン生成を開始する
         * @description 検索条件を受け取り、プラン生成ジョブを開始して即座に `planId` を返す。
         *     外部 API 3 種 + LLM で合計 8〜15 秒かかるため同期では返さない。
         *     進捗は `GET /v1/plans/{planId}/events` (SSE) で購読する。
         */
        post: operations["createPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plans/{planId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * プランを取得する
         * @description 生成中の場合も 200 を返し、`data.status` で進捗を示す。
         *     `status` が `completed` / `partial` 以外のとき `timeline` は空配列または部分配列になる。
         */
        get: operations["getPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plans/{planId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * プラン生成の進捗を SSE で購読する
         * @description `text/event-stream`。イベント名と data は以下の通り。
         *
         *     | event      | data                                   |
         *     |------------|----------------------------------------|
         *     | `status`   | `{ "status": "collecting" }`           |
         *     | `sources`  | `SourceStatus`（各 API が返り次第 1 件ずつ） |
         *     | `plan`     | `Plan`（完成時に 1 回。GET と同一形状）   |
         *     | `error`    | `ErrorBody`                            |
         *
         *     `plan` または `error` の送信後、サーバはストリームを閉じる。
         */
        get: operations["streamPlanEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clicks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * アフィリエイトリンクのクリックを記録する
         * @description フロントの `AffiliateLink` コンポーネントからのみ呼ばれる。
         *     リンク遷移をブロックしないよう `sendBeacon` / `keepalive` での送信を想定し、
         *     本文の検証に失敗しても 204 を返す（計測のためにユーザー体験を止めない）。
         */
        post: operations["recordClick"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ヘルスチェック */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description ULID ベースのプラン ID
         * @example pln_01HX8Z9K3M4N5P6Q7R8S9T0V1W
         */
        PlanId: string;
        /**
         * @description FactStore が採番する候補 ID。**LLM が参照できる唯一の識別子**であり、
         *     Hydrator は FactStore に存在しない ID を含む LLM 出力を棄却する。
         * @example cand_dining_003
         */
        CandidateId: string;
        Location: {
            lat: number;
            lng: number;
        };
        /** @description 円（整数）。`max` 省略は上限なし。 */
        MoneyRangeJpy: {
            /** @default 0 */
            min: number;
            max?: number;
        };
        SearchRequest: {
            event: components["schemas"]["EventInput"];
            party?: components["schemas"]["PartyInput"];
            situation: components["schemas"]["SituationInput"];
            dining?: components["schemas"]["DiningPreference"];
            lodging?: components["schemas"]["LodgingPreference"];
            returnTrip?: components["schemas"]["ReturnTripPreference"];
            options?: components["schemas"]["PlanOptions"];
            context?: components["schemas"]["RequestContext"];
        };
        EventInput: {
            /**
             * @description イベントマスタ参照時のみ。手入力なら null。
             * @default null
             */
            eventId: string | null;
            /** @example ○○ TOUR 2026 東京公演 */
            name?: string;
            venue: components["schemas"]["VenueInput"];
            /**
             * Format: date-time
             * @description **全計算の起点**。RFC3339 かつオフセット必須。過去日時は 400。
             * @example 2026-09-12T21:00:00+09:00
             */
            endsAt: string;
            /**
             * @description 規制退場・物販待ちの余裕（分）。
             * @default 30
             */
            exitBufferMinutes: number;
        };
        VenueInput: {
            /** @example 東京ドーム */
            name: string;
            address?: string;
            location: components["schemas"]["Location"];
            /**
             * @description あれば経路精度が上がる。
             * @example ChIJK1kFhcSMGGARFwQMs73Kejo
             */
            googlePlaceId?: string | null;
        };
        PartyInput: {
            /** @default 2 */
            adults: number;
            /** @default 0 */
            children: number;
            /**
             * @default friends
             * @enum {string}
             */
            relationship: "solo" | "couple" | "friends" | "family";
        };
        /**
         * @description **このアプリの差別化点**。`mood` と `notes` は Go の絞り込みには一切使わず、
         *     LLM のプロンプトにのみ渡して文章生成の文脈にする。
         */
        SituationInput: {
            /**
             * @description stay=宿泊前提 / return=帰宅前提 / either=Go が終電可否で判断
             * @enum {string}
             */
            intent: "stay" | "return" | "either";
            /** @default [] */
            mood: ("celebrate" | "relaxed" | "efficient" | "budget")[];
            /**
             * @description 自由記述。LLM へそのまま渡すためプロンプトインジェクション対策の対象。
             * @example 初めての遠征で土地勘がありません。荷物が多めです。
             */
            notes?: string;
            physicalLimit?: {
                /** @default 15 */
                maxWalkMinutes: number;
            };
        };
        DiningPreference: {
            /** @default true */
            enabled: boolean;
            /** @default [] */
            genres: ("izakaya" | "ramen" | "yakiniku" | "sushi" | "cafe" | "bar" | "family_restaurant" | "fast_food" | "italian" | "chinese")[];
            budgetPerPersonJpy?: components["schemas"]["MoneyRangeJpy"];
            /** @default [] */
            requirements: ("open_late" | "reservable" | "non_smoking" | "private_room" | "all_you_can_drink" | "vegetarian_ok")[];
            /** @default 90 */
            desiredStayMinutes: number;
        };
        LodgingPreference: {
            /** @default true */
            enabled: boolean;
            /**
             * Format: date
             * @description 日付のみが意味を持つため date 形式。
             */
            checkInDate?: string;
            /** Format: date */
            checkOutDate?: string;
            /** @default 1 */
            rooms: number;
            budgetPerNightJpy?: components["schemas"]["MoneyRangeJpy"];
            /** @default [] */
            requirements: ("no_smoking" | "late_checkin_ok" | "with_bath" | "large_bath" | "breakfast_included" | "coin_laundry" | "free_wifi")[];
        };
        /** @description `situation.intent` が return / either のときのみ有効。 */
        ReturnTripPreference: {
            destination?: {
                /** @enum {string} */
                type: "station" | "address" | "airport";
                /** @example 新宿 */
                name: string;
            };
            /** @default true */
            checkLastTrain: boolean;
        };
        PlanOptions: {
            /**
             * @description Google Routes API の travelMode に対応。
             * @default [
             *       "WALK",
             *       "TRANSIT"
             *     ]
             */
            transportModes: ("WALK" | "TRANSIT" | "DRIVE" | "BICYCLE")[];
            /**
             * @description **LLM 入力トークン量を直接決めるコスト制御ノブ**。
             *     8 件 x 3 カテゴリで入力 3〜5K トークン程度。
             * @default 8
             */
            maxCandidatesPerCategory: number;
            /**
             * @description false なら LLM をスキップし、ルールベースで時系列のみ組む。
             * @default true
             */
            llmNarrative: boolean;
        };
        RequestContext: {
            /** @default ja-JP */
            locale: string;
            /**
             * @default JPY
             * @enum {string}
             */
            currency: "JPY";
            /** @default Asia/Tokyo */
            timezone: string;
        };
        PlanCreatedEnvelope: {
            data: {
                planId: components["schemas"]["PlanId"];
                status: components["schemas"]["PlanStatus"];
                /**
                 * Format: uri-reference
                 * @example /v1/plans/pln_01HX8Z9K3M4N5P6Q7R8S9T0V1W/events
                 */
                streamUrl?: string;
            };
            meta: components["schemas"]["Meta"];
        };
        PlanEnvelope: {
            data: components["schemas"]["Plan"];
            meta: components["schemas"]["Meta"];
        };
        /**
         * @description queued → collecting（3 API 並行取得中）→ composing（LLM 生成中）→ completed。
         *     一部プロバイダが落ちても組めた場合は partial。
         * @enum {string}
         */
        PlanStatus: "queued" | "collecting" | "composing" | "completed" | "partial" | "failed";
        Plan: {
            planId: components["schemas"]["PlanId"];
            status: components["schemas"]["PlanStatus"];
            /** Format: date-time */
            generatedAt: string;
            /**
             * Format: date-time
             * @description **空室情報の鮮度保証**。既定 15 分。期限切れをフロントが検知して再検索を促し、
             *     「クリックしたら満室だった」という最も痛い離脱を防ぐ。
             */
            expiresAt?: string;
            /** Format: uri */
            shareUrl?: string;
            /** @description LLM 由来。options.llmNarrative が false のとき、および LLM 全滅時は null。 */
            narrative: components["schemas"]["PlanNarrative"] | null;
            summary: components["schemas"]["PlanSummary"];
            timeline: components["schemas"]["Segment"][];
            alternatives: components["schemas"]["Alternatives"];
            warnings: components["schemas"]["Warning"][];
        };
        /** @description **LLM が生成した文章のみ**を格納する。事実は一切含まない。 */
        PlanNarrative: {
            /** @example 終演の余韻を、水道橋の深夜に持ち帰る */
            title: string;
            summary: string;
            closingNote?: string | null;
            /** @example relaxed_late_night */
            vibe?: string | null;
        };
        /** @description **Go が確定した事実のみ**。LLM は書き込めない。 */
        PlanSummary: {
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            totalWalkMinutes: number;
            totalWalkMeters: number;
            estimatedCostJpy: {
                dining?: number;
                lodging?: number;
                transit?: number;
                total: number;
            };
            /**
             * @description tight = 乗り換え・入店の余裕が 5 分未満の箇所がある。
             * @enum {string}
             */
            feasibility: "ok" | "tight" | "infeasible";
        };
        /** @description **LLM 由来**。UI から消しても機能が落ちない層。 */
        SegmentNarrative: {
            headline: string;
            reason?: string | null;
            tip?: string | null;
        };
        SegmentBase: {
            id: string;
            type: components["schemas"]["SegmentType"];
            /**
             * Format: date-time
             * @description Go の timecalc が endsAt 起点で累積計算した絶対時刻。
             */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            durationMinutes: number;
            narrative: components["schemas"]["SegmentNarrative"] | null;
        };
        /** @enum {string} */
        SegmentType: "buffer" | "move" | "dining" | "lodging";
        /** @description `type` による判別可能ユニオン。フロントの SegmentCard が唯一のディスパッチャ。 */
        Segment: components["schemas"]["BufferSegment"] | components["schemas"]["MoveSegment"] | components["schemas"]["DiningSegment"] | components["schemas"]["LodgingSegment"];
        BufferSegment: components["schemas"]["SegmentBase"] & {
            /** @constant */
            type: "buffer";
            buffer: components["schemas"]["BufferDetail"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "buffer";
        };
        MoveSegment: components["schemas"]["SegmentBase"] & {
            /** @constant */
            type: "move";
            move: components["schemas"]["MoveDetail"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "move";
        };
        DiningSegment: components["schemas"]["SegmentBase"] & {
            /** @constant */
            type: "dining";
            dining: components["schemas"]["DiningDetail"];
            links: components["schemas"]["Link"][];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "dining";
        };
        LodgingSegment: components["schemas"]["SegmentBase"] & {
            /** @constant */
            type: "lodging";
            lodging: components["schemas"]["LodgingDetail"];
            links: components["schemas"]["Link"][];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "lodging";
        };
        BufferDetail: {
            /** @enum {string} */
            kind: "exit_congestion" | "goods_queue" | "spare_time";
            atPlaceName?: string;
        };
        /** @description **Google Routes API 由来（LLM 不可侵）**。 */
        MoveDetail: {
            /** @enum {string} */
            travelMode: "WALK" | "TRANSIT" | "DRIVE" | "BICYCLE";
            distanceMeters: number;
            durationMinutes: number;
            from: components["schemas"]["Waypoint"];
            to: components["schemas"]["Waypoint"];
            /** @description 地図描画用のエンコード済みポリライン。 */
            encodedPolyline?: string | null;
            /** Format: uri */
            mapsUrl?: string | null;
            /** @default [] */
            transitLegs: components["schemas"]["TransitLeg"][];
        };
        Waypoint: {
            name: string;
            location: components["schemas"]["Location"];
        };
        /** @description travelMode が TRANSIT のときのみ。 */
        TransitLeg: {
            /** @example JR中央・総武線 */
            lineName: string;
            headsign?: string | null;
            departureStop: string;
            arrivalStop: string;
            /** Format: date-time */
            departureAt?: string | null;
            /** Format: date-time */
            arrivalAt?: string | null;
            numStops?: number | null;
            fareJpy?: number | null;
        };
        /** @description **Google Places API 由来（LLM 不可侵）**。 */
        DiningDetail: {
            candidateId: components["schemas"]["CandidateId"];
            providerPlaceId: string;
            name: string;
            /** @default [] */
            genres: string[];
            rating?: number | null;
            userRatingCount?: number | null;
            priceLevel?: number | null;
            estimatedCostPerPersonJpy?: number | null;
            address?: string | null;
            location: components["schemas"]["Location"];
            /**
             * Format: uri
             * @description Places の写真は自前 CDN 経由でプロキシする（キー秘匿とキャッシュのため）。
             */
            photoUrl?: string | null;
            phoneNumber?: string | null;
            openingStatus?: components["schemas"]["OpeningStatus"] | null;
        };
        OpeningStatus: {
            /** @description 到着予定時刻（現在時刻ではない）における営業判定。 */
            openNow: boolean;
            /** Format: date-time */
            opensAt?: string | null;
            /** Format: date-time */
            closesAt?: string | null;
        };
        /** @description **楽天トラベル API 由来（LLM 不可侵）**。 */
        LodgingDetail: {
            candidateId: components["schemas"]["CandidateId"];
            providerHotelId: string;
            name: string;
            reviewAverage?: number | null;
            reviewCount?: number | null;
            address?: string | null;
            location: components["schemas"]["Location"];
            /** Format: uri */
            photoUrl?: string | null;
            plan: components["schemas"]["LodgingPlanDetail"];
        };
        LodgingPlanDetail: {
            providerPlanId: string;
            planName: string;
            roomName?: string | null;
            totalPriceJpy: number;
            pricePerPersonJpy?: number | null;
            /** @enum {string} */
            vacancyStatus: "available" | "few_left" | "sold_out";
            remainingRooms?: number | null;
            /** @example 15:00 */
            checkInTime?: string | null;
            /**
             * @description 24 時超えを 26:00 のように表記する提供元仕様をそのまま保持する。
             * @example 26:00
             */
            checkInDeadline?: string | null;
            /** @example 10:00 */
            checkOutTime?: string | null;
            /** @default [] */
            amenities: string[];
        };
        /**
         * @description **収益がかかっている唯一の出口**。素の URL 文字列を置かず必ずこの構造にすることで、
         *     ASP 追加時の全画面改修を防ぎ、`rel="sponsored"` とクリック計測を
         *     `AffiliateLink` コンポーネント 1 つで担保する。
         */
        Link: {
            /** @enum {string} */
            kind: "affiliate" | "official" | "tel" | "map";
            /** @enum {string} */
            provider: "rakuten_travel" | "hotpepper" | "gurunavi" | "google_maps" | "direct";
            label: string;
            /** @description affiliate の場合は完成済みアフィリエイト URL。tel の場合は tel: スキーム。 */
            url: string;
            /** @description POST /v1/clicks に送る計測 ID。kind=affiliate では必須。 */
            trackingId?: string | null;
        };
        /** @description UI の AlternativePicker が使う差し替え候補。 */
        Alternatives: {
            /** @default [] */
            dining: components["schemas"]["DiningAlternative"][];
            /** @default [] */
            lodging: components["schemas"]["LodgingAlternative"][];
        };
        DiningAlternative: components["schemas"]["DiningDetail"] & {
            /** @description LLM の unusedCandidateNotes 由来。採用しなかった理由。 */
            excludedReason?: string | null;
            links?: components["schemas"]["Link"][];
        };
        LodgingAlternative: components["schemas"]["LodgingDetail"] & {
            excludedReason?: string | null;
            links?: components["schemas"]["Link"][];
        };
        Warning: {
            /** @enum {string} */
            code: "VACANCY_LOW" | "LAST_TRAIN_MISSED" | "NO_LODGING_FOUND" | "NO_DINING_FOUND" | "WALK_LIMIT_EXCEEDED" | "BUDGET_EXCEEDED" | "PROVIDER_DEGRADED" | "LLM_UNAVAILABLE" | "TIGHT_SCHEDULE";
            /** @enum {string} */
            severity: "info" | "warning" | "critical";
            segmentId?: string | null;
            message: string;
        };
        /**
         * @description 並行 fan-out の部分失敗を隠さず返すための観測情報。
         *     楽天が落ちても飲食店だけ返して `partial` にするほうが、全体 500 より UX が良い。
         */
        Meta: {
            requestId: string;
            /** @default [] */
            sources: components["schemas"]["SourceStatus"][];
            llm?: components["schemas"]["LlmMeta"] | null;
        };
        SourceStatus: {
            /** @enum {string} */
            provider: "google_places" | "google_routes" | "rakuten_travel";
            /** @enum {string} */
            status: "ok" | "degraded" | "failed" | "skipped";
            latencyMs: number;
            cached: boolean;
            /** @default 0 */
            resultCount: number;
            error?: components["schemas"]["ErrorBody"] | null;
        };
        LlmMeta: {
            /** @enum {string} */
            provider: "anthropic" | "google" | "rule_based";
            /** @example claude-opus-5 */
            model: string;
            /** @example plan_output.v1 */
            schemaVersion: string;
            /** @example plan_v1 */
            promptVersion: string;
            latencyMs?: number;
            inputTokens?: number;
            outputTokens?: number;
            /**
             * @description Validator 不合格による再生成回数。**プロンプト品質の実測値**なので
             *     CloudWatch に流して改善サイクルを回す。
             * @default 0
             */
            repairAttempts: number;
        };
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        ErrorBody: {
            /** @example VALIDATION_FAILED */
            code: string;
            message: string;
            /** @default [] */
            details: {
                field: string;
                reason: string;
            }[];
            requestId?: string | null;
        };
        ClickRequest: {
            planId: components["schemas"]["PlanId"];
            segmentId?: string | null;
            trackingId: string;
            /** @enum {string} */
            provider?: "rakuten_travel" | "hotpepper" | "gurunavi" | "google_maps" | "direct";
            /** Format: date-time */
            clickedAt?: string;
        };
    };
    responses: {
        /** @description リクエストが不正 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 対象が存在しない */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description レート制限 */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description サーバ内部エラー */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        PlanId: components["schemas"]["PlanId"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description 生成ジョブを受け付けた */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanCreatedEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    getPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description プラン（生成中を含む） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description プランの有効期限（expiresAt）が切れている */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    streamPlanEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE ストリーム */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    recordClick: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClickRequest"];
            };
        };
        responses: {
            /** @description 記録した（検証失敗時も 204） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 正常 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                        version?: string;
                    };
                };
            };
        };
    };
}
